In [20]:
import pandas as pd

df_movies = pd.read_csv("D:\\Projects\\ML\\pet-recommendation\\datasets\\movies.dat",
                        sep='::', engine='python',
                        encoding="Latin-1",
                        names=['movie_id', 'title', 'genre'])

df_rating = pd.read_csv("D:\\Projects\\ML\\pet-recommendation\\datasets\\ratings.dat",
                        sep='::', engine='python',
                        encoding="Latin-1",
                        names=['user_id', 'movie_id', 'rating', 'timestamp'])

df_users = pd.read_csv("D:\\Projects\\ML\\pet-recommendation\\datasets\\users.dat",
                       sep='::', engine='python',
                       encoding="Latin-1",
                       names=["user_id", "gender", "age_group", "occupation", "zip_code"])

In [4]:
df_users.head()

   user_id gender  age_group  occupation zip_code
0        1      F          1          10    48067
1        2      M         56          16    70072
2        3      M         25          15    55117
3        4      M         45           7    02460
4        5      M         25          20    55455

Из интересного в таблице наблюдаю пол, возрастную группу и професия (нам она не известна, но для модели может быть полезно)

In [5]:
df_rating.head()

   user_id  movie_id  rating  timestamp
0        1      1193       5  978300760
1        1       661       3  978302109
2        1       914       3  978301968
3        1      3408       4  978300275
4        1      2355       5  978824291

На основе пользователей и фильмов можно будет сделать матрицу факторизации для лучшего отсева рекомендаций после получения самых популярных фильмов

In [6]:
df_movies.head()

   movie_id                              rating                         genre
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy

Жанры точно надо будет использовать при постоении модели

In [19]:
interactions = df_rating.copy()

popularity = (
    interactions.groupby("movie_id").rating
    .agg(
        count="count",
        mean="mean"
    )
    .reset_index()
    .sort_values(by=["count", "mean"], ascending=False)
)

popularity

user_id = 2651
k = 10

watched_movies = set(
    interactions.loc[
        interactions.user_id == user_id, "movie_id"
    ]
)

recommendations = (
    popularity.loc[
        ~popularity.movie_id.isin(watched_movies)
    ]
    .reset_index()
    .head(k)
)

recommendations

   index  movie_id  count      mean
0   2651      2858   3428  4.317386
1   1120      1210   2883  4.022893
2   1178      1270   2583  3.990321
3    579       593   2578  4.351823
4   1449      1580   2538  3.739953
5    593       608   2513  4.254676
6   2557      2762   2459  4.406263
7   2203      2396   2369  4.127480
8   1107      1197   2318  4.303710
9    513       527   2304  4.510417